/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Tue Apr 14 11:22:26 2026


#include "WhisperSpeechTranscription_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(WhisperSpeechTranscriptionParamsCOMPONENT, "yarp.device.WhisperSpeechTranscription")
}


WhisperSpeechTranscription_ParamsParser::WhisperSpeechTranscription_ParamsParser()
{
}


std::vector<std::string> WhisperSpeechTranscription_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("model_context");
    params.push_back("model_name");
    params.push_back("language");
    params.push_back("remove_symbols");
    return params;
}


bool WhisperSpeechTranscription_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="model_context")
    {
        paramValue = m_model_context;
        return true;
    }
    if (paramName =="model_name")
    {
        paramValue = m_model_name;
        return true;
    }
    if (paramName =="language")
    {
        paramValue = m_language;
        return true;
    }
    if (paramName =="remove_symbols")
    {
        paramValue = std::to_string(m_remove_symbols);
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string WhisperSpeechTranscription_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      WhisperSpeechTranscription_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter model_context
    {
        if (config.check("model_context"))
        {
            m_model_context = config.find("model_context").asString();
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'model_context' using value:" << m_model_context;
        }
        else
        {
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'model_context' using DEFAULT value:" << m_model_context;
        }
        prop_check.unput("model_context");
    }

    //Parser of parameter model_name
    {
        if (config.check("model_name"))
        {
            m_model_name = config.find("model_name").asString();
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'model_name' using value:" << m_model_name;
        }
        else
        {
            yCError(WhisperSpeechTranscriptionParamsCOMPONENT) << "Mandatory parameter 'model_name' not found!";
            yCError(WhisperSpeechTranscriptionParamsCOMPONENT) << "Description of the parameter: name of Whisper model";
            return false;
        }
        prop_check.unput("model_name");
    }

    //Parser of parameter language
    {
        if (config.check("language"))
        {
            m_language = config.find("language").asString();
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'language' using value:" << m_language;
        }
        else
        {
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'language' using DEFAULT value:" << m_language;
        }
        prop_check.unput("language");
    }

    //Parser of parameter remove_symbols
    {
        if (config.check("remove_symbols"))
        {
            m_remove_symbols = config.find("remove_symbols").asInt64();
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'remove_symbols' using value:" << m_remove_symbols;
        }
        else
        {
            yCInfo(WhisperSpeechTranscriptionParamsCOMPONENT) << "Parameter 'remove_symbols' using DEFAULT value:" << m_remove_symbols;
        }
        prop_check.unput("remove_symbols");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(WhisperSpeechTranscriptionParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(WhisperSpeechTranscriptionParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      WhisperSpeechTranscription_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: WhisperSpeechTranscription\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'model_context': context of Whisper model\n");
    doc = doc + std::string("'model_name': name of Whisper model\n");
    doc = doc + std::string("'language': Language (??? TBC)\n");
    doc = doc + std::string("'remove_symbols': If symbols from output text, (i.e. ...[bla bla]...) are removed\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device yarp_whisperSpeechTranscription --model_context <optional_value> --model_name <mandatory_value> --language auto --remove_symbols 1\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device yarp_whisperSpeechTranscription --model_name <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
