/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Tue Apr 14 11:22:26 2026


#ifndef WHISPERSPEECHTRANSCRIPTION_PARAMSPARSER_H
#define WHISPERSPEECHTRANSCRIPTION_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class WhisperSpeechTranscription.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                                                     | Notes                     |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:---------------------------------------------------------------:|:-------------------------:|
* | -          | model_context  | string | -     | -             | 0        | context of Whisper model                                        | Here are additional notes |
* | -          | model_name     | string | -     | -             | 1        | name of Whisper model                                           | Here are additional notes |
* | -          | language       | string | -     | auto          | 0        | Language (??? TBC)                                              | Here are additional notes |
* | -          | remove_symbols | int    | -     | 1             | 0        | If symbols from output text, (i.e. ...[bla bla]...) are removed | Here are additional notes |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device yarp_whisperSpeechTranscription --model_context <optional_value> --model_name <mandatory_value> --language auto --remove_symbols 1
* \endcode
*
* \code{.unparsed}
* yarpdev --device yarp_whisperSpeechTranscription --model_name <mandatory_value>
* \endcode
*
*/

class WhisperSpeechTranscription_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    WhisperSpeechTranscription_ParamsParser();
    ~WhisperSpeechTranscription_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"WhisperSpeechTranscription"};
    const std::string m_device_name = {"yarp_whisperSpeechTranscription"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_model_context_defaultValue = {""};
    const std::string m_model_name_defaultValue = {""};
    const std::string m_language_defaultValue = {"auto"};
    const std::string m_remove_symbols_defaultValue = {"1"};

    std::string m_model_context = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    std::string m_model_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_language = {"auto"};
    int m_remove_symbols = {1};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
